---
output: html_document
theme: yeti
---

<br>
<center>#**Research**
<br>
###I’m a PhD Candidate in Ecology at UC Davis, in the Karban and Holyoak labs. I did my M.S. in the Elkinton lab at University of Massachusetts Amherst, and a Fulbright fellowship with Birchmoth at University of Tromsø and the Norwegian Institute for Nature Research. I’m currently an (informal) visiting scholar with Jenny Cory at Simon Fraser University and Judy Myers at University of British Columbia.
<br>
###I’m interested broadly in plant-insect population & community ecology, especially in the context of climate change. I also have an interest in the ecology and biological control of invasive insects.
<br>
###In terms of the effects of climate change on populations and communities, I’m interested in 1. causes of geographic variation in climate effects on population dynamics, 2. effects of changing patterns of climate variation on population dynamics, 3. temperature effects on ectotherm predator-prey interactions. In terms of invasive insect biological control, I am interested in applying ecological theory to understand factors controlling invasive species dynamics, to aid in control efforts. Past biological control efforts suggest that not all species are amenable to natural enemy importation as a means of control, or that some natural enemies are effective controls and others are not. To address questions in these research areas, I use a combination of observational and experimental fieldwork, time series and statistical modelling, and mathematical and simulation models.